'use client';
import { FormEvent, useEffect, useState } from 'react';
export default function AccountPage(){
 const [status,setStatus]=useState<{email:string;emailVerified:boolean;emailVerificationRequired:boolean;twoFactorEnabled:boolean}|null>(null);
 const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [secret,setSecret]=useState('');const [codes,setCodes]=useState<string[]>([]);const [link,setLink]=useState<{action:string;token:string}|null>(null);
 useEffect(()=>{const fragment=new URLSearchParams(location.hash.slice(1));for(const action of ['verify','reset']){const token=fragment.get(action);if(token){setLink({action,token});history.replaceState(null,'',location.pathname);}}
 fetch('/api/community/account/status',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.json()).then(d=>{if(d.email)setStatus(d);}).catch(()=>setNotice('Account information could not be loaded.'));},[]);
 async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();setBusy(true);setNotice('');const fields=Object.fromEntries(new FormData(event.currentTarget));
 try{const response=await fetch(`/api/community/account/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,token:link?.token})});if(response.ok && action==='export'){const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cia-guide-account.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Account export downloaded.');return;}const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');
 if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cia-guide-account.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Account export downloaded.');}else setNotice(data.message||'Completed.');
 if(data.secret)setSecret(data.secret);if(data.codes){setCodes(data.codes);setSecret('');}if(['delete','mfa-confirm','mfa-disable'].includes(action))setStatus(null);
 }catch(error){setNotice(error instanceof Error?error.message:'Request failed.');}finally{setBusy(false);}}
 const credentials=<><label>Current password<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label><label>Authenticator or recovery code (if enabled)<input name="code" autoComplete="one-time-code" maxLength={32}/></label></>;
 return <main className="form-page"><a href="/">Back to the guide</a><section className="form-card"><h1>Account &amp; privacy</h1><p>You can read every FAQ without joining. Sign up and verify your email to interact with other parents and students.</p><p><a href="/community">Sign in or create an account</a> · <a href="/privacy">Privacy details</a></p><p role="status" aria-live="polite">{busy?'Working…':notice}</p>
 {link&&<form onSubmit={e=>submit(e,link.action)}><h2>{link.action==='verify'?'Verify email':'Choose a new password'}</h2>{link.action==='reset'&&<label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{12,128}" title="Use 12–128 characters with an uppercase letter, lowercase letter, number, and symbol." required/></label>}<button disabled={busy}>Confirm {link.action==='verify'?'email':'new password'}</button></form>}
 <form onSubmit={e=>submit(e,'reset-request')}><h2>Forgot your password?</h2><label>Email<input name="email" type="email" autoComplete="email" required maxLength={200}/></label><button disabled={busy}>Send password reset link</button></form>
 {status&&<><h2>{status.email}</h2><p>Email: {status.emailVerified?'verified':status.emailVerificationRequired?'verification needed':'verification is not required until email delivery is configured'}. Two-factor authentication: {status.twoFactorEnabled?'on':'off'}.</p>{status.emailVerificationRequired&&!status.emailVerified&&<form onSubmit={e=>submit(e,'verify-request')}><button disabled={busy}>Send verification email</button></form>}
 {(!status.emailVerificationRequired||status.emailVerified)&&<><form onSubmit={e=>submit(e,secret?'mfa-confirm':status.twoFactorEnabled?'mfa-disable':'mfa-setup')}><h2>Two-factor authentication</h2><p>Use an authenticator app. Recovery codes let you sign in if you lose access to that app.</p>{secret&&<p>Setup key: <code style={{overflowWrap:'anywhere'}}>{secret}</code>. Enter it in your authenticator, then confirm with its six-digit code.</p>}{credentials}<button disabled={busy}>{secret?'Confirm setup':status.twoFactorEnabled?'Disable two-factor authentication':'Set up two-factor authentication'}</button></form>
 <form onSubmit={e=>submit(e,'export')}><h2>Download your information</h2><p>Download your account details, posts, comments, reactions, reports and wall submissions as JSON. Uploaded photo files are included as base64 data in the JSON export.</p>{credentials}<button disabled={busy}>Download account data</button></form>
 <form onSubmit={e=>submit(e,'delete')}><h2>Delete your account</h2><p>This permanently removes your account, community content and associated wall submissions, including uploaded images. Other members’ copies cannot be removed.</p>{credentials}<label>Type DELETE MY ACCOUNT<input name="confirmation" required/></label><button disabled={busy}>Permanently delete account</button></form></>}
 </>}{codes.length>0&&<section><h2>Save your recovery codes</h2><p>Each code works once. These will not be shown again.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{codes.join('\n')}</pre></section>}</section></main>;
}
