'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from "next/link";
import { COMMUNITY_TOPICS, MEMBER_TYPES, STUDENT_STAGES } from "../community-onboarding";
export default function AccountPage(){
 const [status,setStatus]=useState<{email:string;emailVerified:boolean;emailVerificationRequired:boolean;twoFactorEnabled:boolean;avatarUrl?:string|null}|null>(null);
 const [avatarMessage,setAvatarMessage]=useState('');
 const [onboarding,setOnboarding]=useState({memberType:'parent_guardian',studentStage:'prefer_not_to_say',topics:[] as string[],safetyAccepted:false});
 const [preferencesMessage,setPreferencesMessage]=useState('');
 const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [secret,setSecret]=useState('');const [codes,setCodes]=useState<string[]>([]);const [link,setLink]=useState<{action:string;token:string}|null>(null);
 useEffect(()=>{const fragment=new URLSearchParams(location.hash.slice(1));for(const action of ['verify','reset']){const token=fragment.get(action);if(token){setLink({action,token});history.replaceState(null,'',location.pathname);}}
 fetch('/api/community/account/status',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.json()).then(d=>{if(d.email)setStatus(d);}).catch(()=>setNotice('Account information could not be loaded.'));
 fetch('/api/community/account/onboarding').then(r=>r.json()).then(d=>{if(d.onboarding)setOnboarding({...d.onboarding,safetyAccepted:false});}).catch(()=>{});},[]);
 async function submit(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();setBusy(true);setNotice('');const fields=Object.fromEntries(new FormData(event.currentTarget));
 try{const response=await fetch(`/api/community/account/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,token:link?.token})});if(response.ok && action==='export'){const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cia-guide-account.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Account export downloaded.');return;}const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');
 if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cia-guide-account.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Account export downloaded.');}else setNotice(data.message||'Completed.');
 if(data.secret)setSecret(data.secret);if(data.codes){setCodes(data.codes);setSecret('');}if(['delete','mfa-confirm','mfa-disable'].includes(action))setStatus(null);
 }catch{setNotice('That request could not be completed. Please try again.');}finally{setBusy(false);}}
 async function savePreferences(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setPreferencesMessage('');try{const response=await fetch('/api/community/account/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(onboarding)});const data=await response.json();if(!response.ok)throw new Error(data.error);setPreferencesMessage('Community preferences saved.');}catch{setPreferencesMessage('Preferences could not be saved. Please try again.');}finally{setBusy(false);}}
 async function uploadAvatar(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setAvatarMessage('');try{const form=new FormData(event.currentTarget);const response=await fetch('/api/community/profile/avatar',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setAvatarMessage('Profile photo updated.');setStatus(current=>current?{...current,avatarUrl:data.avatarUrl}:current);event.currentTarget.reset();}catch(error){setAvatarMessage(error instanceof Error?error.message:'Profile photo could not be updated.');}finally{setBusy(false);}}
 const credentials=<><label>Current password<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label><label>Authenticator or recovery code (if enabled)<input name="code" autoComplete="one-time-code" maxLength={32}/></label></>;
 return <main className="cia-community c-account-page"><div className="c-account-shell"><Link className="c-account-back" href="/community">← Back to community</Link><section className="c-account-card"><h1>Account &amp; privacy</h1><p>Manage your community profile, sign-in security, privacy, and community preferences here.</p><p><Link href="/community">Community</Link> · <Link href="/privacy">Privacy details</Link></p><p role="status" aria-live="polite">{busy?'Working…':notice}</p>
 {link&&<form onSubmit={e=>submit(e,link.action)}><h2>{link.action==='verify'?'Verify email':'Choose a new password'}</h2>{link.action==='reset'&&<label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{12,128}" title="Use 12–128 characters with an uppercase letter, lowercase letter, number, and symbol." required/></label>}<button disabled={busy}>Confirm {link.action==='verify'?'email':'new password'}</button></form>}
 <form onSubmit={e=>submit(e,'reset-request')}><h2>Forgot your password?</h2><label>Email<input name="email" type="email" autoComplete="email" required maxLength={200}/></label><button disabled={busy}>Send password reset link</button></form>
 {status&&<><h2>{status.email}</h2><form onSubmit={uploadAvatar}><h2>Profile photo</h2><p>Add a photo that community members can recognize. JPG, PNG, or WebP; up to 5 MB.</p>{status.avatarUrl&&<img src={status.avatarUrl} alt="Current profile" style={{width:96,height:96,borderRadius:'50%',objectFit:'cover'}}/>}<label>Choose photo<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp" required/></label><button disabled={busy}>Upload profile photo</button><p role="status">{avatarMessage}</p></form><p>Email: {status.emailVerified?'verified':'verification needed'}. Two-factor authentication: {status.twoFactorEnabled?'on':'off'}.</p>{!status.emailVerified&&<form onSubmit={e=>submit(e,'verify-request')}><button disabled={busy}>Send verification email</button></form>}
 <form onSubmit={savePreferences}><h2>Community preferences</h2><p>These private answers help organize conversations. Do not add student names, IDs, room numbers, schedules, health details, or exact locations.</p><label>You are joining as<select value={onboarding.memberType} onChange={event=>setOnboarding({...onboarding,memberType:event.target.value})}>{MEMBER_TYPES.map(value=><option key={value} value={value}>{({parent_guardian:'Parent or guardian',family_support:'Family member/support person',cia_student:'CIA student',other_supporter:'Other community supporter'} as Record<string,string>)[value]}</option>)}</select></label><label>Where is your student in the CIA journey?<select value={onboarding.studentStage} onChange={event=>setOnboarding({...onboarding,studentStage:event.target.value})}>{STUDENT_STAGES.map(value=><option key={value} value={value}>{({currently_attending:'Currently attending Hyde Park',starting_spring_2027:'Starting Spring 2027',starting_future:'Starting in a future term',exploring:'Exploring or preparing to apply',prefer_not_to_say:'Prefer not to say'} as Record<string,string>)[value]}</option>)}</select></label><fieldset><legend>Topics that would be useful</legend>{COMMUNITY_TOPICS.map(topic=><label key={topic}><input type="checkbox" checked={onboarding.topics.includes(topic)} onChange={event=>setOnboarding({...onboarding,topics:event.target.checked?[...onboarding.topics,topic]:onboarding.topics.filter(value=>value!==topic)})}/>{topic}</label>)}</fieldset><label><input type="checkbox" checked={onboarding.safetyAccepted} onChange={event=>setOnboarding({...onboarding,safetyAccepted:event.target.checked})}/> I will not post student passwords, IDs, room numbers, live schedules, private medical details, or photos of someone else without permission.</label><button disabled={busy}>Save community preferences</button><p role="status">{preferencesMessage}</p></form>
 {(!status.emailVerificationRequired||status.emailVerified)&&<><form onSubmit={e=>submit(e,secret?'mfa-confirm':status.twoFactorEnabled?'mfa-disable':'mfa-setup')}><h2>Two-factor authentication</h2><p>Use an authenticator app. Recovery codes let you sign in if you lose access to that app.</p>{secret&&<p>Setup key: <code style={{overflowWrap:'anywhere'}}>{secret}</code>. Enter it in your authenticator, then confirm with its six-digit code.</p>}{credentials}<button disabled={busy}>{secret?'Confirm setup':status.twoFactorEnabled?'Disable two-factor authentication':'Set up two-factor authentication'}</button></form>
 <form onSubmit={e=>submit(e,'export')}><h2>Download your information</h2><p>Download your account details, posts, comments, reactions, reports and wall submissions as JSON. Uploaded photo files are included as base64 data in the JSON export.</p>{credentials}<button disabled={busy}>Download account data</button></form>
 <form onSubmit={e=>submit(e,'delete')}><h2>Delete your account</h2><p>This permanently removes your account, community content and associated wall submissions, including uploaded images. Other members&rsquo; copies cannot be removed.</p><button disabled={busy}>Delete my account</button></form></>}
 </>}{codes.length>0&&<section><h2>Save your recovery codes</h2><p>Each code works once. These will not be shown again.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{codes.join('\n')}</pre></section>}</section></div></main>;
}
