/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SupportRouteImport } from './routes/support'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as FaqTopicRouteImport } from './routes/faq.$topic'
import { Route as ApiPublicInstagramCalendarImportRouteImport } from './routes/api/public/instagram-calendar-import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FaqRoute,
} as any)
const FaqTopicRoute = FaqTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => FaqRoute,
} as any)
const ApiPublicInstagramCalendarImportRoute =
  ApiPublicInstagramCalendarImportRouteImport.update({
    id: '/api/public/instagram-calendar-import',
    path: '/api/public/instagram-calendar-import',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/corrections': typeof CorrectionsRoute
  '/faq': typeof FaqRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/share': typeof ShareRoute
  '/shopping': typeof ShoppingRoute
  '/support': typeof SupportRoute
  '/faq/$topic': typeof FaqTopicRoute
  '/faq/': typeof FaqIndexRoute
  '/api/public/instagram-calendar-import': typeof ApiPublicInstagramCalendarImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/corrections': typeof CorrectionsRoute
  '/moderation': typeof ModerationRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/share': typeof ShareRoute
  '/shopping': typeof ShoppingRoute
  '/support': typeof SupportRoute
  '/faq/$topic': typeof FaqTopicRoute
  '/faq': typeof FaqIndexRoute
  '/api/public/instagram-calendar-import': typeof ApiPublicInstagramCalendarImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/corrections': typeof CorrectionsRoute
  '/faq': typeof FaqRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/share': typeof ShareRoute
  '/shopping': typeof ShoppingRoute
  '/support': typeof SupportRoute
  '/faq/$topic': typeof FaqTopicRoute
  '/faq/': typeof FaqIndexRoute
  '/api/public/instagram-calendar-import': typeof ApiPublicInstagramCalendarImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/community'
    | '/corrections'
    | '/faq'
    | '/moderation'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/safety'
    | '/share'
    | '/shopping'
    | '/support'
    | '/faq/$topic'
    | '/faq/'
    | '/api/public/instagram-calendar-import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/community'
    | '/corrections'
    | '/moderation'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/safety'
    | '/share'
    | '/shopping'
    | '/support'
    | '/faq/$topic'
    | '/faq'
    | '/api/public/instagram-calendar-import'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/community'
    | '/corrections'
    | '/faq'
    | '/moderation'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/safety'
    | '/share'
    | '/shopping'
    | '/support'
    | '/faq/$topic'
    | '/faq/'
    | '/api/public/instagram-calendar-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  CorrectionsRoute: typeof CorrectionsRoute
  FaqRoute: typeof FaqRouteWithChildren
  ModerationRoute: typeof ModerationRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SafetyRoute: typeof SafetyRoute
  ShareRoute: typeof ShareRoute
  ShoppingRoute: typeof ShoppingRoute
  SupportRoute: typeof SupportRoute
  ApiPublicInstagramCalendarImportRoute: typeof ApiPublicInstagramCalendarImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof FaqRoute
    }
    '/faq/$topic': {
      id: '/faq/$topic'
      path: '/$topic'
      fullPath: '/faq/$topic'
      preLoaderRoute: typeof FaqTopicRouteImport
      parentRoute: typeof FaqRoute
    }
    '/api/public/instagram-calendar-import': {
      id: '/api/public/instagram-calendar-import'
      path: '/api/public/instagram-calendar-import'
      fullPath: '/api/public/instagram-calendar-import'
      preLoaderRoute: typeof ApiPublicInstagramCalendarImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FaqRouteChildren {
  FaqTopicRoute: typeof FaqTopicRoute
  FaqIndexRoute: typeof FaqIndexRoute
}

const FaqRouteChildren: FaqRouteChildren = {
  FaqTopicRoute: FaqTopicRoute,
  FaqIndexRoute: FaqIndexRoute,
}

const FaqRouteWithChildren = FaqRoute._addFileChildren(FaqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  CorrectionsRoute: CorrectionsRoute,
  FaqRoute: FaqRouteWithChildren,
  ModerationRoute: ModerationRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SafetyRoute: SafetyRoute,
  ShareRoute: ShareRoute,
  ShoppingRoute: ShoppingRoute,
  SupportRoute: SupportRoute,
  ApiPublicInstagramCalendarImportRoute: ApiPublicInstagramCalendarImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
